<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NaveenK" name="ChromeTest" tests="5" failures="0" timestamp="12 Oct 2019 12:54:09 GMT" time="2.848" errors="0">
  <testcase name="@BeforeMethod setupTest" time="0.0" classname="Mytests.FirstTest">
    <failure type="org.openqa.selenium.remote.UnreachableBrowserException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;NAVEENK&amp;apos;, ip: &amp;apos;192.168.99.1&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_211&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'NAVEENK', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at Mytests.BaseTest.setupTest(BaseTest.java:28)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Failed to connect to /192.168.99.100:4446
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	... 26 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 48 more
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setupTest" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setupTest" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterClass terminate" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- @AfterClass terminate -->
  <testcase name="@BeforeMethod setupTest" time="0.0" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setupTest" time="0.0" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterClass terminate" time="0.0" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- @AfterClass terminate -->
  <testcase name="FacebookTest" time="0.001" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- FacebookTest -->
  <testcase name="GmailTest" time="0.0" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- GmailTest -->
  <testcase name="InstagramTest" time="0.001" classname="Mytests.FirstTest">
    <skipped/>
  </testcase> <!-- InstagramTest -->
  <testcase name="MyntraTest" time="0.0" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- MyntraTest -->
  <testcase name="ThoughtWorksTest" time="0.001" classname="Mytests.SecondTest">
    <skipped/>
  </testcase> <!-- ThoughtWorksTest -->
</testsuite> <!-- ChromeTest -->
